title: Julien Liabeuf
description: I am a Bangkok-based Business Developer and Product Manager. On this blog, I share my thoughts on business and IT."
tagline: Product Manager, Business Developer

url: https://julienliabeuf.com
baseurl: ""
paginate_path: "blog/page/:num/"
permalink: :title/

repository: julien731/blog-jekyll

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

author:
  name: Julien Liabeuf

social:
   github: julien731
   twitter: julien731
   email: julien@liabeuf.fr
   googleplus: +JulienLiabeuf

google_analytics: "UA-22409901-4"

# reCAPTCHA
reCaptcha:
  enabled: true
  siteKey: "6Lcl_WYUAAAAABOmMBvZ8IV24VpQRPwVPx89FiOp"
  secret: "Ph1ZcUu2A/F8ZasP86TE8J6ORO4NPQ1yCRmo5QiLDtP7OA/6aCQozNOrjZx+FZ6EhVGttmueTaK6BH7hmqBqWhTLC1pbMqcuoTOGFpOXTb8x1FGudRamJ3V++IX23Hx3l4vk9LqU34l3YSrZ5iEDCbjzgC2F4aZ0L8iMfpNC+Bo="